### ISSUE TITLE
编译时候报错

### ISSUE THREAD

**Issue by makeloveandroid** [MegatronKing/StringFog#1]
Error:Execution failed for task ':stringfog-sample:transformClassesWithExtractJarsForDebug'.
> error

**Comment by makeloveandroid** [comment]
原因：

    更新到 Android Studio 2.0 以后的新特性：instant run 即使运行功能 (.......)

解决方案：

    settings -> Build，Execution，Deployment ->Instant Run -> Enable Instant Run ... 去掉勾选

**Comment by makeloveandroid** [comment]
原因：
    更新到 Android Studio 2.0 以后的新特性：instant run 即使运行功能 (.......)
解决方案：
    settings -> Build，Execution，Deployment ->Instant Run -> Enable Instant Run ... 去掉勾选

**Comment by MegatronKing** [comment]
确实不支持Instant Run，看了下transform的时候和transformClassesWithExtractJarsForDebug任务有冲突
