### ISSUE TITLE
StringFogExtension的fogPackages不能被赋值，Val cannot be reassigned

### ISSUE THREAD

**Issue by phoenixsky** [MegatronKing/StringFog#106]
![image](https://user-images.githubusercontent.com/6359214/233366091-1897bc27-61ac-483a-a8fc-417217b33e37.png)
如上图。
最近在用kts写插件，想在插件中直接使用stringfog（仿nowinandroid项目的build-logic），出现了以上问题
不知道groovy的
```
String[] fogPackages = []
```
为什么在kt中不能被赋值。因为是数组，长度又确认了，也无法setIndex。

**Comment by ucxl** [comment]
等作者更新，希望支持到agp8.0

**Comment by MegatronKing** [comment]
5.x版本已支持agp 8.0
