### ISSUE TITLE
Application的string没被混淆

### ISSUE THREAD

**Issue by lileii** [MegatronKing/StringFog#108]
我发现两个问题：
1.Application的string没被混淆
2. Intent intent = new Intent(this, WebViewActivity.class);
        intent.putExtra("url", str);
        finish();
        这里的url字符串没被混淆

**Comment by lileii** [comment]
问题2的这个activity 是整个App的启动类

//stringfog {
//    // 必要：加解密库的实现类路径，需和上面配置的加解密算法库一致。
//    implementation 'com.github.megatronking.stringfog.xor.StringFogImpl'
//    // 可选：加密开关，默认开启。
//    enable true
//    debug true
//    // 可选：指定需加密的代码包路径，可配置多个，未指定将默认全部加密。
////        fogPackages = ['com.xxx.xxx']
//    // 可选（3.0版本新增）：指定密钥生成器，默认使用长度8的随机密钥（每个字符串均有不同随机密钥）,
//    // 也可以指定一个固定的密钥：HardCodeKeyGenerator("This is a key")
//    // 可选（4.0版本新增）：用于控制字符串加密后在字节码中的存在形式, 默认为base64，
//    // 也可以使用text或者bytes
//    mode base64
//}


我的配置如下

**Comment by lileii** [comment]
我用的的是7.4.1

**Comment by MegatronKing** [comment]
同 #111

**Comment by lileii** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
