### ISSUE TITLE
Unable to resolve applicationID

### ISSUE THREAD

**Issue by TheRangerStar** [MegatronKing/StringFog#115]
我的SDK 32 最小 23 ,JDK 17  buildConfig true 也有。 用的也是5.0.0，gradle 8.0，然后都配置完，build 就报Unable to resolve applicationID

**Comment by RepeatAfterMe** [comment]
add package="your.packagename.app" in your AndroidManifest.xml

**Comment by luckyzyx** [comment]
在AndroidManifest.xml 添加包名
![image](https://github.com/MegatronKing/StringFog/assets/46274354/11b05f40-d365-4e68-b065-2c587110dccc)

**Comment by mosentest** [comment]
https://github.com/MegatronKing/StringFog/pull/125

**Comment by MegatronKing** [comment]
v5.1.0已更新，请再试试，如果还有问题请参考文档配置packageName。
