### ISSUE TITLE
StringFogExtension报错

### ISSUE THREAD

**Issue by Fayeang** [MegatronKing/StringFog#116]
![image](https://github.com/MegatronKing/StringFog/assets/20484355/7912d40b-e804-473c-9dee-bbb5d0eb4d33)
![image](https://github.com/MegatronKing/StringFog/assets/20484355/871b19ff-66f5-4d83-9971-5247f980d5f8)
![image](https://github.com/MegatronKing/StringFog/assets/20484355/90ba0e7b-cea6-4310-b225-c27096222bcb)
最后这个一直报错，Unresolved reference: StringFogExtension；
大佬帮忙看一下

**Comment by MegatronKing** [comment]
按照文档操作，不应该有这种问题。这个issue我先关闭了，如果还有问题再打开。

**Comment by hw1020** [comment]
建议 步骤上价格提示，加入以来后要把依赖同步拉取下来再去配置后面的配置信息，不然容易出现按配置弄完了，一点同步就报错，就不会拉取依赖的jar包，就会报这个错误。

**Comment by renliwenwen** [comment]
我也遇到了相同的问题， 你怎么解决的呀

**Comment by Ercilan** [comment]
`import com.github.megatronking.stringfog.plugin.StringFogExtension`
