### ISSUE TITLE
  id 'stringfog' 以后就报错，版本是4.0.1

### ISSUE THREAD

**Issue by uyevan** [MegatronKing/StringFog#118]
Missing stringfog implementation config

**Comment by luckyzyx** [comment]
> Missing stringfog implementation config

![image](https://github.com/MegatronKing/StringFog/assets/46274354/ade8fdc0-b828-4e8c-9f01-2bf8b21c5bc6)

**Comment by MegatronKing** [comment]
4.x已经不维护了，建议升级到5.x。
