### ISSUE TITLE
5.0.0 build.gradle8.0遇到的报错

### ISSUE THREAD

**Issue by unitycl** [MegatronKing/StringFog#120]
A problem occurred evaluating project ':app'.
> Could not get unknown property 'base64' for extension 'stringfog' of type com.github.megatronking.stringfog.plugin.StringFogExtension.

**Comment by NewMacPro** [comment]
me too

**Comment by mosentest** [comment]
A problem occurred evaluating project ':app'.
> Could not get unknown property 'base64' for extension 'stringfog' of type com.github.megatronking.stringfog.plugin.StringFogExtension.

**Comment by mosentest** [comment]
@MegatronKing

**Comment by mosentest** [comment]
Unable to resolve applicationId

**Comment by mosentest** [comment]
Caused by: java.lang.IllegalArgumentException: Unable to resolve applicationId
	at com.github.megatronking.stringfog.plugin.StringFogPlugin$apply$1.invoke(StringFogPlugin.kt:50)
	at com.github.megatronking.stringfog.plugin.StringFogPlugin$apply$1.invoke(StringFogPlugin.kt:28)
	at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl$onVariants$1.execute(AndroidComponentsExtensionImpl.kt:72)

**Comment by mosentest** [comment]
val applicationId = parsedManifest.attribute("package")?.toString()
            if (applicationId.isNullOrEmpty()) {
                throw IllegalArgumentException("Unable to resolve applicationId")
            }



作者校验了这里

**Comment by mosentest** [comment]
自己在manifest加下
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="${applicationId}">

**Comment by mosentest** [comment]
Incorrect package="com.mosen.xxxx.xxxx" found in source AndroidManifest.xml: /Users/admin/git_me_pro/xxxxxx/app/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="com.xxxx.xxxxx.huawei" from the source AndroidManifest.xml: /Users/admin/git_me_pro/xxxxx/app/src/main/AndroidManifest.xml.


不过新版本不允许加package，你们自己要么降级下gradle吧

**Comment by mosentest** [comment]
注释namespace，会报错。把studio卸载吧

Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

android {
    namespace 'com.example.namespace'
}

If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

**Comment by mosentest** [comment]
https://github.com/MegatronKing/StringFog/pull/125

**Comment by Sohoad** [comment]
![image](https://github.com/MegatronKing/StringFog/assets/102650432/b1be361f-34b3-48c0-8e65-65b0a9ab9a4c)
这样就可以了

**Comment by Sohoad** [comment]
![image](https://github.com/MegatronKing/StringFog/assets/102650432/acf480fe-ea2f-479b-a4fd-ea0fce5cbf99)
这样就可以了

**Comment by MegatronKing** [comment]
已更新v5.1.0和readme文档。
