### ISSUE TITLE
Cannot invoke "java.io.BufferedWriter.newLine()" because "this.mWriter" is null这个报错如何解决

### ISSUE THREAD

**Issue by Sohoad** [MegatronKing/StringFog#126]
Gradle 8.0 StringFog5.0.0编译后出现Cannot invoke "java.io.BufferedWriter.newLine()" because "this.mWriter" is null
已尝试buildFeatures   buildConfig = true , 清理项目也试过, 依旧无法 编译

**Comment by lic2050** [comment]
老哥这个问题解决了吗？ @Sohoad

**Comment by yuqiaodan** [comment]
删除app下的build文件 直接打包就可以了 目前只能这样  开发完毕最后一步再引入stringfog

**Comment by nick-oc** [comment]
我加入下面的代码指定了加密包好像就没再出现这个问题了
fogPackages = arrayOf("com.xx.xx")// 可选：指定需加密的代码包路径

**Comment by Sohoad** [comment]
> 老哥这个问题解决了吗？ @Sohoad 

还没法解决，每次编译前结束下 java.exe 清除下项目

**Comment by MegatronKing** [comment]
v5.1.0已暂时移除stringfog.txt文件生成。
