### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lxx/xxx/xxxxx/StringFog;

### ISSUE THREAD

**Issue by Krosxx** [MegatronKing/StringFog#127]
agp: 8.1

一开始构建是能正常生成 `StringFog.java` ，但是后面不知道为什么 一直生成不了，打的 apk 里面字符串已加密，但是不包含 `StringFog` 这个类，并且generated/source/**buildConfig**/{varant}/{appId}  下没有 `StringFog.java`  只有 `BuildConfig.java`；且 `outputs/mapping/xxx/stringfog.txt` 文件内容是空的。

另外，前几次构建上面粗体为大写 `BuildConfig` (也不行)，不知为何现在变为 `buildConfig`.  

请教下出现此问题可能得情况有哪些呢？

**Comment by shichuanenhui** [comment]
同样的问题，我打包后apk也不包含{包名.StringFog}这个类, 导致程序打开就崩溃

**Comment by shichuanenhui** [comment]
作者看看怎么解决这个bug

**Comment by xujiaji** [comment]
请问有解决吗？

**Comment by MegatronKing** [comment]
v5.1.0版本应该解决了这个问题。
