### ISSUE TITLE
enable为false，为什么会有如下生成，这个生成导致编译速度很慢？

### ISSUE THREAD

**Issue by gaofeidisanbu** [MegatronKing/StringFog#128]
![image](https://github.com/MegatronKing/StringFog/assets/25192134/ad3e3d0d-5c9e-4745-a3f3-2ce117979c2e)

**Comment by MegatronKing** [comment]
缓存？还是修改配置后没有sync？

**Comment by gaofeidisanbu** [comment]
不是，我用的4.0，debug环境，每次clean之后，再运行，也会生成这些

**Comment by gaofeidisanbu** [comment]
![image](https://github.com/MegatronKing/StringFog/assets/25192134/c884a173-ca8e-44a5-bdfe-f73d4eeeca72)

**Comment by MegatronKing** [comment]
4.x已经不维护了，还是试试5.x版本吧。
