### ISSUE TITLE
Gradle 8.0.2  StringFog 5.0 几个问题解决方法,和一个疑似BUG

### ISSUE THREAD

**Issue by arneking** [MegatronKing/StringFog#129]
gradle 版本 8.0.2 碰到的问题

1.app build.gradle  snyc 报错
stringfog {
    ......
    mode bytes
}

解决方法:
import com.github.megatronking.stringfog.plugin.StringFogMode
stringfog {
    ......
    mode StringFogMode.bytes
}

2.编译报错 Unable to resolve applicationId
AndroidManifest.xml  manifest 标签内添加 package="xxxx"

3.编译报错 Cannot invoke "java.io.BufferedWriter.newLine()" because "this.mWriter" is null
这个疑似是个BUG   ..\build\outputs\mapping\release or debug\stringfog.txt 文件被占用,里面也没任何信息
无法使用 clear project ,退出重开Android Studio可以解决一次....下次编译继续报错
还有一个简单粗暴的方法...不用退出Android Studio,直接任务管理器结束所有 java.exe 进程...重新编译即可

**Comment by yuqiaodan** [comment]
可以可以 解决很多问题了

**Comment by MegatronKing** [comment]
v5.1.0已修复。
