### ISSUE TITLE
请求扩展提供对已经编译好的Dex或者jar 文件进行字符串加密。

### ISSUE THREAD

**Issue by RFSN** [MegatronKing/StringFog#134]
开源作者您好。
感谢你提供对应字符串加密的工具，
不知道是否能提供对已经编译好的Dex或者jar 文件进行字符串加密。
或者基于现有的代码有通过 jar -jar 类似的命令实现该扩展功能吗？

**Comment by MegatronKing** [comment]
这个不在StringFog的功能范围呢。
