### ISSUE TITLE
部分字段无法加密

### ISSUE THREAD

**Issue by chancey0126** [MegatronKing/StringFog#139]
发现Log无法加密，其他部分自定义常量也没法加密
<img width="617" alt="Xnip2023-09-08_10-12-33" src="https://github.com/MegatronKing/StringFog/assets/22585635/a235d809-8285-44af-bdb2-83909f686d78">
<img width="794" alt="Xnip2023-09-08_10-13-59" src="https://github.com/MegatronKing/StringFog/assets/22585635/60843b1e-6607-480d-9a27-6264d0d981eb">

**Comment by BananaHuo** [comment]
我也有这个问题，你解决了吗

**Comment by GarbageCan1024** [comment]
我想知道怎么把StringFog.decrypt(xxx, xxx)混淆成如上图的w.a(xxx, xxx)
