### ISSUE TITLE
build.gradle.kts DSL 怎么接入

### ISSUE THREAD

**Issue by XjxBoom** [MegatronKing/StringFog#148]
plugins {
    //...lib or application
    id("stringfog")
}
apply(plugin = "stringfog")

configure<StringFogExtension> {
    // 必要：加解密库的实现类路径，需和上面配置的加解密算法库一致。
    implementation = "com.github.megatronking.stringfog.xor.StringFogImpl"
    // 可选：加密开关，默认开启。
    enable = true
    // 可选：指定需加密的代码包路径，可配置多个，未指定将默认全部加密。
    // fogPackages = arrayOf("com.xxx.xxx")
    kg = com.github.megatronking.stringfog.plugin.kg.RandomKeyGenerator()
    // base64或者bytes
    mode = com.github.megatronking.stringfog.plugin.StringFogMode.bytes
}
这样写得话,会提示找不到stringfog
错误信息 :  Missing stringfog implementation config

**Comment by XjxBoom** [comment]
根目录
buildscript {
    dependencies {
        classpath("com.github.megatronking.stringfog:gradle-plugin:5.1.0")
        classpath("com.github.megatronking.stringfog:xor:5.0.0")
    }
}

项目gradle

@Suppress("DSL_SCOPE_VIOLATION") // TODO: Remove once KTIJ-19369 is fixed
plugins {
    alias(libs.plugins.com.android.library)
    alias(libs.plugins.org.jetbrains.kotlin.android)
    id("stringfog")
}
apply(plugin = "stringfog")

**Comment by zhoutianling** [comment]
+1

**Comment by darcycui** [comment]
+1

**Comment by darcycui** [comment]
我搞定了,
1.注释app build.gradle.kts中的stringfog所有相关配置,保留项目build.gradle.kts配置;
2.同步项目
3.放开1中注释
4.编译通过
5.另外 注意app 配置添加泛型StringFogExtension
configure<<StringFogExtension>> {
    // 必要：加解密库的实现类路径，需和上面配置的加解密算法库一致。
    implementation = "com.github.megatronking.stringfog.xor.StringFogImpl"
    // 可选：加密开关，默认开启。
    enable = true
    // 可选：指定需加密的代码包路径，可配置多个，未指定将默认全部加密。
    // fogPackages = arrayOf("com.xxx.xxx")
    kg = com.github.megatronking.stringfog.plugin.kg.RandomKeyGenerator()
    // base64或者bytes
    mode = com.github.megatronking.stringfog.plugin.StringFogMode.bytes
}
![image](https://github.com/user-attachments/assets/e3ae9b06-1cbb-40a1-85b7-d133ce0a7927)
@XjxBoom @zhoutianling
