### ISSUE TITLE
自定义class解密提示无效的实现希望打印e参数。方便定位问题。

### ISSUE THREAD

**Issue by qssq** [MegatronKing/StringFog#19]
```

    public StringFogWrapper(String impl) {
        try {
            mStringFogImpl = (IStringFog) Class.forName(impl).newInstance();
        } catch (Exception e) {
            throw new IllegalArgumentException("Invalid stringfog implementation: " + impl);
        }
    }
```

**Comment by qssq** [comment]
自定义实现不能写在源码里面吗？  非得打包到gradle插件里面才能用的么

**Comment by qssq** [comment]
想改源码，可是迷糊了
    implementation 'com.github.megatronking.stringfog:xor:1.0.0' 和claspath
   'com.github.megatronking.stringfog:xor:1.0.0' 都一样，我的理解中classpath和那个作用应该是不同的呀，为毛能共用同一个东西。

**Comment by qssq** [comment]
大佬能教我测试gradle插件嘛，我基于源码修改只会打出jar包然后再测试。

**Comment by MegatronKing** [comment]
对的，目前自定义算法只能先打成jar包，暂时还不能引用源码，确实是个不太方便，我加到下个版本的规划里面。

**Comment by MegatronKing** [comment]
参数已添加。自定义实现引用源码请看README
