### ISSUE TITLE
在SDK 上使用

### ISSUE THREAD

**Issue by liuwenqiang** [MegatronKing/StringFog#2]
怎么在我自己编写的SDK中使用这个加密 
apply plugin: 'stringfog' 只能添加在 在app的build.gradle中
怎么在 同一个项目中的 module 使用

**Comment by MegatronKing** [comment]
抱歉，这个不支持在Library模块中使用。因为这个插件的原理是编译时使用transform对字节码改写，而Library编译时没有transform操作，所以无法支持。

**Comment by MegatronKing** [comment]
已更新1.2.0，支持在module中使用，各个module可以使用不同的加密key
