### ISSUE TITLE
希望可以加入一個接口

### ISSUE THREAD

**Issue by Anzhi-Meiying** [MegatronKing/StringFog#21]
可以通过gradle里面自定义某个类作为解密类，不然的话感觉好麻烦哎

**Comment by MegatronKing** [comment]
支持配置自定义类作为解密类的，请查看https://github.com/MegatronKing/StringFog#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%A0%E8%A7%A3%E5%AF%86%E7%AE%97%E6%B3%95%E9%9B%86%E6%88%90

**Comment by Anzhi-Meiying** [comment]
@MegatronKing 
![image](https://user-images.githubusercontent.com/13428030/52858601-8a1b1780-3165-11e9-94f4-2ef9d852f833.png)
这个集成具体怎么做...不是很懂
这样子？
![image](https://user-images.githubusercontent.com/13428030/52858624-9e5f1480-3165-11e9-93d6-b227e17f12b3.png)

有具体例子嘛...

**Comment by MegatronKing** [comment]
对的，通过implementation指定，项目里的sample就是例子

**Comment by Anzhi-Meiying** [comment]
@MegatronKing 编译提示 Invalid stringfog implementation
![image](https://user-images.githubusercontent.com/13428030/52859098-c56a1600-3166-11e9-8ec7-2b15088503bf.png)

**Comment by Anzhi-Meiying** [comment]
就是这个buildSrc我不是很懂怎么放...不好意思比较小白

**Comment by MegatronKing** [comment]
加我微信聊
