### ISSUE TITLE
密钥不安全 轻松反编译拿到并且批量解密

### ISSUE THREAD

**Issue by o2e** [MegatronKing/StringFog#24]
可以考虑一个字符串一个随机密钥 这样逆向者只能每个字符串都要去找密钥并解密一次
目前你这种应该可以吧class里面的字符串收集起来统一解密来定位关键代码

**Comment by MegatronKing** [comment]
你说的非常有道理，我这个只是一种思路，纯粹恶心逆向者的，真论加密确实弱

**Comment by WYC-2020** [comment]
> 可以考虑一个字符串一个随机密钥 这样逆向者只能每个字符串都要去找密钥并解密一次 目前你这种应该可以吧class里面的字符串收集起来统一解密来定位关键代码

是的这个想法很好 ，最近刚好用上这个库也发现了这个问题，随机密钥的话可以加大破解的难度，求大佬加上，期待
