### ISSUE TITLE
WARNING: API 'variantOutput.getProcessResources()'

### ISSUE THREAD

**Issue by Anzhi-Meiying** [MegatronKing/StringFog#25]
> implementation 'com.github.megatronking.stringfog:interface:1.0.0'

> WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: app

@MegatronKing

**Comment by MegatronKing** [comment]
根目录下build.gradle里面classpath的gradle版本是多少

**Comment by Anzhi-Meiying** [comment]
@MegatronKing 

> classpath 'com.android.tools.build:gradle:3.4.0'

**Comment by MegatronKing** [comment]
同 #22
