### ISSUE TITLE
find normal field value wrongly

### ISSUE THREAD

**Issue by adrianhsm** [MegatronKing/StringFog#35]
https://github.com/MegatronKing/StringFog/blob/c9d8a4bcf39c9aac6fbe1020ac97d4329b217439/stringfog-gradle-plugin/src/main/java/com/github/megatronking/stringfog/plugin/StringFogClassVisitor.java#L99

it is to add static final to mFields, isn't it wrong?

**Comment by MegatronKing** [comment]
@adrianhsm A mistake and a redundant code. I will remove this, thanks anyway!
