### ISSUE TITLE
classNotFound的错误

### ISSUE THREAD

**Issue by LYC-Android** [MegatronKing/StringFog#39]
stringfog {
    key 'hellow('   // 这是加解密key，可以自由定义
    enable true // 开关
    implementation 'com.github.megatronking.stringfog.xor.StringFogImpl'
}

dependencies {
    implementation 'com.github.megatronking.stringfog:xor:1.1.0'
}

用这样打出来的aar，会没有StringFogImpl这个类，然后就会报classNotFound的错误，然后我自己手动在aar工程加上这个类之后。无论是在aar还是在app里面通过反编译都可以看到这个类，但是还是报找不到这个类的错误，最后需要在app那个build.gradle里面添加这个类的依赖才不报错。挺神奇的

**Comment by LYC-Android** [comment]
用的最新的版本 AS3.3.2

**Comment by MegatronKing** [comment]
未发现此问题。
