### ISSUE TITLE
一键解密

### ISSUE THREAD

**Issue by jinsc123** [MegatronKing/StringFog#41]
目前自带的算法可以被MT一键解密，可有应对办法？如果自己实现加解密算法会被一键解密吗？

**Comment by MegatronKing** [comment]
此项目只是提供一种思路，侧重点不是加密算法，很容易解密。重要的项目建议自己实现加密算法，除非是针对性来解密，通用解密方式基本可防。



---原始邮件---
发件人: "jinsc"<notifications@github.com&gt;
发送时间: 2020年8月12日(周三) 晚上10:00
收件人: "MegatronKing/StringFog"<StringFog@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [MegatronKing/StringFog] 一键解密 (#41)




 
目前自带的算法可以被MT一键解密，可有应对办法？如果自己实现加解密算法会被一键解密吗？

**Comment by shmilylty** [comment]
> 目前自带的算法可以被MT一键解密，可有应对办法？如果自己实现加解密算法会被一键解密吗？

请问一下MT是什么工具呀 有相关的介绍地址吗
