### ISSUE TITLE
请问如何设置StringFog插件在proguard之后执行？

### ISSUE THREAD

**Issue by tangxuesong6** [MegatronKing/StringFog#43]
混淆中使用
```
-assumenoexternalsideeffects class java.lang.StringBuilder {
    public java.lang.StringBuilder();
    public java.lang.StringBuilder(int);
    public java.lang.StringBuilder(java.lang.String);
    public java.lang.StringBuilder append(java.lang.Object);
    public java.lang.StringBuilder append(java.lang.String);
    public java.lang.StringBuilder append(java.lang.StringBuffer);
    public java.lang.StringBuilder append(char[]);
    public java.lang.StringBuilder append(char[], int, int);
    public java.lang.StringBuilder append(boolean);
    public java.lang.StringBuilder append(char);
    public java.lang.StringBuilder append(int);
    public java.lang.StringBuilder append(long);
    public java.lang.StringBuilder append(float);
    public java.lang.StringBuilder append(double);
    public java.lang.String toString();
}

-assumenoexternalreturnvalues public final class java.lang.StringBuilder {
    public java.lang.StringBuilder append(java.lang.Object);
    public java.lang.StringBuilder append(java.lang.String);
    public java.lang.StringBuilder append(java.lang.StringBuffer);
    public java.lang.StringBuilder append(char[]);
    public java.lang.StringBuilder append(char[], int, int);
    public java.lang.StringBuilder append(boolean);
    public java.lang.StringBuilder append(char);
    public java.lang.StringBuilder append(int);
    public java.lang.StringBuilder append(long);
    public java.lang.StringBuilder append(float);
    public java.lang.StringBuilder append(double);
}
```
此配置加上`force "net.sf.proguard:proguard-gradle:6.0.3"`更完整的去掉log日志，即把无用的StringBuilder.append也去掉。但是由于使用了StringFog插件，log日志中的StringBuilder.append就变得有意义了。所以日志没有优化成功。有没有办法让插件在proguard之后执行？比如写个gradle task先执行proguard，再进行字符串混淆？

**Comment by xloger** [comment]
我也有同样的困扰

**Comment by Saint-Theana** [comment]
有办法了
1:   关掉r8
gradle.properties中加入下面几条
android.enableR8.fullMode=false
android.enableR8=false
android.enableR8.libraries=false

2:最外层的build.gradle内的buildscript中加入

buildscript {
...
configurations.all {
        resolutionStrategy {
            dependencySubstitution {
                substitute module('net.sf.proguard:proguard-gradle') with module('com.guardsquare:proguard-gradle:7.0.1')
            }
        }
    }
}

3:然后在app里的build.gradle中修改
buildTypes {
        release {
			...
            minifyEnabled false
            useProguard false
	   shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

然后在app内的build.gradle中的apply plugin: 'stringfog'之前加上apply plugin: 'proguard'

总之就是r8模式没办法在shrink跟d8之前操作class，如果是舍弃r8，在proguard和d8之间还是有余地的。

**Comment by pengweiwww** [comment]
同有这个问题。楼上的方案或许可以解决，但需要舍弃R8，不够完美。
最好的方案是StringFog支持这个功能，自动删除Log.i等日志方法，进一步降低反编译风险~

**Comment by Saint-Theana** [comment]
> 同有这个问题。楼上的方案或许可以解决，但需要舍弃R8，不够完美。 最好的方案是StringFog支持这个功能，自动删除Log.i等日志方法，进一步降低反编译风险~

不是或许，是一定可以，我一直都是这么做的。
r8替换为proguard后的确是可以做到将proguard插到压缩混淆的后面，从而杜绝许多可能发生的问题。

**Comment by tpnet** [comment]
@MegatronKing  大佬有办法直接支持吗，现在问题是这样子的:  打包时在混淆里面使用assumenosideeffects去掉了log，但是反编译后会发现要打印的字符串还在代码里面。
![image](https://user-images.githubusercontent.com/17380722/203275448-d847e5d8-e303-43e0-a20c-133195505150.png)

**Comment by MegatronKing** [comment]
@tpnet 好像某种情况下是有和assumenosideeffects有冲突，但我记不太清了，你有没有用非官方的proguard库？

**Comment by tpnet** [comment]
@MegatronKing  这个问题用的是官方的混淆。   但我昨晚也尝试用了 [第三方proguard库](https://github.com/Guardsquare/proguard)，我自己的代码出现了`method too large`的问题，还有会导致打包出来之后Stringfog类找不到

**Comment by DysaniazzZ** [comment]
> [@MegatronKing](https://github.com/MegatronKing) 大佬有办法直接支持吗，现在问题是这样子的: 打包时在混淆里面使用assumenosideeffects去掉了log，但是反编译后会发现要打印的字符串还在代码里面。 ![image](https://user-images.githubusercontent.com/17380722/203275448-d847e5d8-e303-43e0-a20c-133195505150.png)

@tpnet @MegatronKing 

使用 stringfog 后导致日志无法被完全清楚的问题，后来是怎么解决的呢？

**Comment by tpnet** [comment]
@DysaniazzZ  这个跟stringfog没关系，是混淆assumenosideeffects的问题，去掉log只是去掉了Log的方法，是不会去掉代码里面的字符串。
