### ISSUE TITLE
使用jeb，加密的字符串会被自动解密出来

### ISSUE THREAD

**Issue by CaoMCan** [MegatronKing/StringFog#48]
使用jeb打开apk，在smali界面字符串是加密的，但是查看源码的时候jeb会自动调用字符串后面的StringFog->decrypt()函数，所以在源码中看到的字符串还是明文
![Dingtalk_20210326092703](https://user-images.githubusercontent.com/51430796/112564038-7bf45680-8e15-11eb-9982-91ba4c87ee24.jpg)
![Dingtalk_20210326092714](https://user-images.githubusercontent.com/51430796/112564040-7c8ced00-8e15-11eb-80af-a105f46f1fe9.jpg)

**Comment by gaoyuoppa** [comment]
AndroidKiller，查看源代码，直接明文显示。。。软件很棒，不过只能恶心那些破解小白。。

**Comment by MegatronKing** [comment]
说实话我也没啥好办法，但是我还是升级了3.0.0版本，接口已改。他什么时候跟着改就不知道了。

**Comment by fh2002** [comment]
> 说实话我也没啥好办法，但是我还是升级了3.0.0版本，接口已改。他什么时候跟着改就不知道了。

可以想办法对xor之类的函数进行bytecode进行加密，在java启动的时候进行还原

**Comment by zhaozhangyun** [comment]
解密方法放到so中即可
