### ISSUE TITLE
发现了个疑似bug

### ISSUE THREAD

**Issue by jiayuliang1314** [MegatronKing/StringFog#49]
// normal, in this condition, the value is null.
if ((access & Opcodes.ACC_STATIC) != 0 && (access & Opcodes.ACC_FINAL) != 0) {
  mFields.add(new ClassStringField(name, (String) value));
  value = null;
}

我在看代码的时候，发现此处是否是个bug，是否应该改为（access & Opcodes.ACC_STATIC) == 0 

mFields这个没用到，这个bug也倒是不会影响啥

**Comment by MegatronKing** [comment]
3.0.0已修改
