### ISSUE TITLE
请问怎么配置只针对release包生效

### ISSUE THREAD

**Issue by bjzhou** [MegatronKing/StringFog#54]

**Comment by MegatronKing** [comment]
有个开关enable，release包把值配置称true，否则false

**Comment by aishuidedabai** [comment]
是不是debug包就改成false，或者说true表示debug和release都生效

**Comment by MegatronKing** [comment]
@aishuidedabai 可以这么理解

**Comment by ucxl** [comment]
有没有什么设置自动debug为false，release为true，我加了一行debug false 不生效

**Comment by ucxl** [comment]
有办法了，定义一个方法，然后 enable isReleaseBuildType()
boolean isReleaseBuildType() {
    for(String s : gradle.startParameter.taskNames){
        if (s.contains("Release") | s.contains("release")){
            return true
        }
    }
    return false
}

**Comment by HsXuTao** [comment]
buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'


            apply plugin: 'stringfog'

            stringfog {
                // 这是加解密key，可以自由定义。
                key ''
                // 开关
                enable true
                // 加解密库的实现类路径，需和上面配置的加解密算法库一致。
                implementation 'StringFogImpl'
                // 指定需加密的代码包路径，可配置多个，未指定将默认全部加密。
//                fogPackages = ['com.wangmai.appsdkdex.crypt']
            }
        }
    }

在buildTypes的release里再加入加密逻辑就可以了，你们可以试试
