### ISSUE TITLE
请问一个类里面某个字符串不想被加密应该怎么做呢？

### ISSUE THREAD

**Issue by tpnet** [MegatronKing/StringFog#55]

**Comment by MegatronKing** [comment]
https://github.com/MegatronKing/StringFog#%E6%B3%A8%E8%A7%A3%E5%8F%8D%E5%8A%A0%E5%AF%86

**Comment by tpnet** [comment]
大佬，是类里面的某个字符串不想加密，不是某个类

![image](https://user-images.githubusercontent.com/17380722/143392302-6147d276-2c6d-487b-9f06-57d19fd90f3f.png)
