### ISSUE TITLE
Can't process class [module-info.class] (null)

### ISSUE THREAD

**Issue by summer-zhoujie** [MegatronKing/StringFog#56]
# Config

//root.gradle
```
classpath 'com.github.megatronking.stringfog:gradle-plugin:2.2.1'
        classpath 'com.github.megatronking.stringfog:xor:1.1.0'
```
//app.gradle
```
apply plugin: 'stringfog'
static def getDate() {
    def date = new Date()
    def formattedDate = date.format('yyyyMMdd')
    return formattedDate
}
stringfog {
        // 这是加解密key，可以自由定义。
        key 'luckyfog' + getDate()
        enable true
        // 指定加解密的具体实现类，可以用默认实现的xor库或者aes-cbc库，也可以自己定制实现，记得配置dependencies
        implementation 'com.github.megatronking.stringfog.xor.StringFogImpl'
        // 指定需加密的代码包路径，可配置多个，未指定将默认全部加密。
        fogPackages = ['com.luckstep.main']
    }
```

# 错误信息
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithProguard'.
> java.io.IOException: Can't read [/Users/apple/Documents/AndroidProjects/luckystep/app/build/intermediates/transforms/stringFog/release/30.jar(;;;;;;;**.class)] (Can't process class [module-info.class] (null))

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 58s
```

**Comment by Sacred1993** [comment]
楼主解决了吗？

**Comment by MegatronKing** [comment]
需要详细的信息，例如是哪个依赖库导致的。

**Comment by Hilmican66** [comment]
> # Yapılandırma
> //root.gradle
> 
> ```
> classpath 'com.github.megatronking.stringfog:gradle-plugin:2.2.1'
>         classpath 'com.github.megatronking.stringfog:xor:1.1.0'
> ```
> 
> //app.gradle
> 
> ```
> apply plugin: 'stringfog'
> static def getDate() {
>     def date = new Date()
>     def formattedDate = date.format('yyyyMMdd')
>     return formattedDate
> }
> stringfog {
>         // 这是加解密key，可以自由定义。
>         key 'luckyfog' + getDate()
>         enable true
>         // 指定加解密的具体实现类，可以用默认实现的xor库或者aes-cbc库，也可以自己定制实现，记得配置dependencies
>         implementation 'com.github.megatronking.stringfog.xor.StringFogImpl'
>         // 指定需加密的代码包路径，可配置多个，未指定将默认全部加密。
>         fogPackages = ['com.luckstep.main']
>     }
> ```
> 
> # 错误信息
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:minifyReleaseWithProguard'.
> > java.io.IOException: Can't read [/Users/apple/Documents/AndroidProjects/luckystep/app/build/intermediates/transforms/stringFog/release/30.jar(;;;;;;;**.class)] (Can't process class [module-info.class] (null))
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4m 58s
> ```

Haha
