### ISSUE TITLE
这个属性怎么无法跳转？

### ISSUE THREAD

**Issue by chaolei-peng** [MegatronKing/StringFog#62]
![E71TA_`DPI1Q6~4M12 HCG](https://user-images.githubusercontent.com/16797866/154916943-6db402f3-41ed-432b-9cda-15468ba9acda.png)
阅读大佬的源码，发现这个无法跳转是为什么？

**Comment by chaolei-peng** [comment]
我看类里面也没有这个属性

**Comment by chaolei-peng** [comment]
莫非指向的是build.gradle 里面的android?

**Comment by MegatronKing** [comment]
@chaolei-peng 是的，其实就是AGP。

**Comment by chaolei-peng** [comment]
感谢大佬回答，这是groovy对DSL比较特别的一点嘛，我用kotlin来写插件demo发现没法像你的代码一样直接点扩展的配置属性，IDE无法识别，还是要create获取扩展对象在访问

**Comment by chaolei-peng** [comment]
感谢大佬回答，这是groovy语言的特性么，我用kotlin来写插件demo发现没法像你的代码一样直接点扩展的配置属性，会爆红

**Comment by MegatronKing** [comment]
和语言没关系，IDE支持的问题

**Comment by chaolei-peng** [comment]
好的，谢谢

**Comment by chaolei-peng** [comment]
![image](https://user-images.githubusercontent.com/16797866/155131307-e26a026d-5e14-409f-ad3a-982bdec4d1ec.png)
大佬请教下这段代码我用kotlin写，尝试了很多种写法，不知道咋写，这闭包跟这个map该怎么传参？

**Comment by chaolei-peng** [comment]
请教大佬这个该怎么传
![image](https://user-images.githubusercontent.com/16797866/155273385-a7eafb54-579b-45b2-9073-a01fed0b6db5.png)
