### ISSUE TITLE
Java 11 AGP 7.0.4 编译报错NestHost requires ASM7

### ISSUE THREAD

**Issue by coolfeng168** [MegatronKing/StringFog#64]
Execution failed for task ':App:transformClassesWithStringFogForDebug'.
> NestHost requires ASM7

**Comment by ucxl** [comment]
改成java1.8

**Comment by coolfeng168** [comment]
> 

Android 12要Java 11

**Comment by ucxl** [comment]
这个java11要作者修复，作者大大也可以看看这个项目 https://github.com/MichaelRocks/paranoid
是支持java11的

**Comment by MegatronKing** [comment]
v4.0.0已支持ASM7
