### ISSUE TITLE
kg new RandomKeyGenerator()

### ISSUE THREAD

**Issue by lishangwl** [MegatronKing/StringFog#65]
RandomKeyGenerator()在哪里参考

**Comment by lishangwl** [comment]
build.gradle': 16: unable to resolve class RandomKeyGenerator 
   @ line 16, column 8.
         kg new RandomKeyGenerator()

**Comment by sonicepro** [comment]
![image](https://user-images.githubusercontent.com/25153556/155969710-fa34e6cf-0ce4-4b89-ae3c-4ef82850b5ac.png)
同问，这怎么解决

**Comment by MegatronKing** [comment]
- 默认不填kg就是RandomKeyGenerator，直接删掉。
-  报红是因为build.gradle里面没有import包，导个包或者写全名com.github.megatronking.stringfog.plugin.kg.RandomKeyGenerator

**Comment by sonicepro** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Megatron ***@***.***&gt;; 
发送时间: 2022年2月28日(星期一) 晚上6:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MegatronKing/StringFog] kg new RandomKeyGenerator() (Issue #65)





  
默认不填kg就是RandomKeyGenerator，直接删掉。
 
报红是因为build.gradle里面没有import包，导个包或者写全名com.github.megatronking.stringfog.plugin.kg.RandomKeyGenerator
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sonicepro** [comment]
大佬，有个想法不知道有没有意义。就是编译的时候把缩进给去掉，让所有代码变成一行，加大反编译后的阅读难度




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MegatronKing/StringFog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 晚上6:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MegatronKing/StringFog] kg new RandomKeyGenerator() (Issue #65)





  
默认不填kg就是RandomKeyGenerator，直接删掉。
 
报红是因为build.gradle里面没有import包，导个包或者写全名com.github.megatronking.stringfog.plugin.kg.RandomKeyGenerator
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MegatronKing** [comment]
@sonicepro 缩进和编译本身没有关系，所以和反编译也没有关系。举个栗子，写代码的时候用2个空格缩进和4个空格缩进，编译的结果是一模一样的，因为缩进不是语法定义也不是语法规则。你用jadx等反编译工具看到有缩进，那也是别人自己加的。
