### ISSUE TITLE
3.0.0加密后，导致包体积变大四分之一

### ISSUE THREAD

**Issue by tpnet** [MegatronKing/StringFog#68]
您好，有些应用对包体积要求非常高。 使用1.1.0的时候，包体为485kb，但是新版3.0.0之后包体变成了662kb，大了四分之一多。 这个有办法控制一下体积吗？  已经设置了fogPackages只加密自己的包名了。
![image](https://user-images.githubusercontent.com/17380722/161997351-88ab8d48-e919-422a-9a7d-01e49e45aee6.png)

**Comment by MegatronKing** [comment]
v4.0.0我加回了base64形式（默认选项），依然可以设置选择v3.0.0的字节数组模式，具体看readme。
