### ISSUE TITLE
4.0终于可以用java 11了

### ISSUE THREAD

**Issue by ucxl** [MegatronKing/StringFog#84]
4.0终于可以用java 11了，感谢作者大大！自定义的加密还不会弄防止mt一键解密

**Comment by MegatronKing** [comment]
可以在这个地方做一些检测，或者把解密用NDK实现：https://github.com/MegatronKing/StringFog-Sample2/blob/004d4b60f1d47378c8101867c6b78e5375efe916/buildSrc/src/main/java/com/github/megatronking/stringfog/sample2/CustomStringFogImpl.java#L25

**Comment by ucxl** [comment]
用反射

    private final Method descriptor = CustomStringFogImpl.class.getDeclaredMethods()[0];

    public static String _decrypt(byte[] data, byte[] key) { return new String(xor(data, key), StandardCharsets.UTF_8);}
    
    @Override
    public String decrypt(byte[] data, byte[] key) {
        try {
            return (String) descriptor.invoke(null, data, key);
        } catch (ReflectiveOperationException e) {
            return null;
        }
    }

**Comment by MegatronKing** [comment]
防止解密的讨论移至 #88
