### ISSUE TITLE
[Suggestion] Doing the same with NDK

### ISSUE THREAD

**Issue by redmi111** [MegatronKing/StringFog#85]
Is it somehow possible to do the same method but with NDK so it'll be faster during the runtime. I'm not sure if it is possible tho.

**Comment by MegatronKing** [comment]
Of course you can, trying to call native method here: https://github.com/MegatronKing/StringFog-Sample2/blob/004d4b60f1d47378c8101867c6b78e5375efe916/buildSrc/src/main/java/com/github/megatronking/stringfog/sample2/CustomStringFogImpl.java#L25
