### ISSUE TITLE
java.util.Base64报错

### ISSUE THREAD

**Issue by 1976222027** [MegatronKing/StringFog#87]
报错   
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
at com.jeacher.app.StringFog.decrypt(StringFog.java:13)

根据java.util.Base64 documentation，它只在API26中添加。在此之前，惟一的应用程序接口是android.util.Base64 class

**Comment by redmi111** [comment]
Yeah, I had faced the same issue. @MegatronKing Consider adding device API version check and use correct package to call Base64 class.

**Comment by MegatronKing** [comment]
已解决，更新4.0.1版本
