### ISSUE TITLE
Gradle3.0编译报错

### ISSUE THREAD

**Issue by Specher** [MegatronKing/StringFog#9]
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Unexpected scopes found in folder 'E:\CloneProject\VirtualCamera\app\build\intermediates\transforms\stringFog\release'. Required: PROJECT, SUB_PROJECTS, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, PROJECT_LOCAL_DEPS, SUB_PROJECTS, SUB_PROJECTS_LOCAL_DEPS

**Comment by stytooldex** [comment]
+1

**Comment by adhere534** [comment]
Error:Execution failed for task ':app:transformClassesWithStringFogForRelease'.
> java.util.zip.ZipException: attempt to write past end of STORED entry

**Comment by MegatronKing** [comment]
same as #5

**Comment by MegatronKing** [comment]
Fix in 1.3.0
