### ISSUE TITLE
idea: StringFog for Android (for IDEs)

### ISSUE THREAD

**Issue by hasrat-ali** [MegatronKing/StringFog#94]
I wanted to implement StringFog in my IDE. So can you separate plugin sources to module. Ex: `stringfog-gradle-plugin` as it is now. And other `core` sources [java](https://github.com/MegatronKing/StringFog/tree/master/stringfog-gradle-plugin/src/main/java/com/github/megatronking/stringfog/plugin)   of stringfog to `stringfog-core`.

**Comment by hasrat-ali** [comment]
Or should I open a pr?

**Comment by MegatronKing** [comment]
Your idea looks good. But I am not familiar with IDE, is code separate necessary?

**Comment by hasrat-ali** [comment]
There's some app like [Sketchware Pro ](https://github.com/Sketchware-Pro/Sketchware-Pro), Code Assist and AndroidIDE. They provide android development on Android phone.

**Comment by MegatronKing** [comment]
> Or should I open a pr?

Welcome!

**Comment by hasrat-ali** [comment]
Thanks
