### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by PoisonGZ** [MegatronKing/StringFog#97]
An exception occurred applying plugin request [id: 'stringfog']
> Failed to apply plugin 'stringfog'.
   > API 'android.registerTransform' is removed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by PoisonGZ** [comment]
希望作者能有空回复一下，谢谢

**Comment by MegatronKing** [comment]
AGP版本太高了，好像是8.0 gradle api变更后不支持transform了

**Comment by PoisonGZ** [comment]
好的，谢谢作者，希望作者有空可以适配一下
