### ISSUE TITLE
AGP 7.4.1 打包不生效

### ISSUE THREAD

**Issue by imliujun** [MegatronKing/StringFog#98]
AGP 7.4.1 打包不生效，最终字符串没有加密

**Comment by hasrat-ali** [comment]
AGP 's transformation api is deprecated in newer version but StringFog still using an old version of AGP.

**Comment by imliujun** [comment]
> AGP 's transformation api is deprecated in newer version but StringFog still using an old version of AGP.

Seeing that you have submitted a PR, can you release a plugin for use first?

**Comment by hasrat-ali** [comment]
Well, StringFog need one step ahead and migrate to Gradle's Transform API.
Maybe i can work on that tomorrow.

But it's depends on @MegatronKing when he merge.

**Comment by MegatronKing** [comment]
5.0.0已经支持。
