### ISSUE TITLE
打包重复问题 com.arialyy.aria.core.download.AbsGroupTaskWrapper

### ISSUE THREAD

**Issue by Warkey1991** [MegatronKing/StringFog#99]
Execution failed for task ':app:mergeProjectDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.arialyy.aria.core.download.AbsGroupTaskWrapper is defined multiple times:

**Comment by zhouyu260** [comment]
怎么解决的？
